"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Dna, HeartPulse, Network, Shield, Trophy } from "lucide-react";
import Sidebar from "../../components/Sidebar";
import Topbar from "../../components/Topbar";
import Breadcrumb from "../../components/Breadcrumb";
import { useHorseCatalog } from "../../lib/useHorseCatalog";
import type { Horse } from "../../lib/horses";

const COLORS = ["#07553a", "#2f855a", "#c59a3b", "#6f59a8", "#d45b5b", "#4389c7"];
const averageScore = (horse: Horse) => { const values=(horse.breedingValue||"").split("-").map(Number).filter(Number.isFinite); return values.length ? values.reduce((a,b)=>a+b,0)/values.length : 0; };

export default function SeljermePage() {
  const [open,setOpen]=useState(false); const {horses}=useHorseCatalog();
  const data=useMemo(()=>{const champions=horses.filter(h=>h.champion); const relations=horses.reduce((n,h)=>n+Number(!!h.father)+Number(!!h.mother),0); const lineageMap=horses.reduce<Record<string,number>>((a,h)=>{const k=h.lineage?.replace(" nesil ugry","")||"Görkezilmedik";a[k]=(a[k]||0)+1;return a;},{}); const lineages=Object.entries(lineageMap).sort((a,b)=>b[1]-a[1]); const yearMap=horses.reduce<Record<string,number>>((a,h)=>{a[h.year]=(a[h.year]||0)+1;return a;},{}); const years=Object.entries(yearMap).sort((a,b)=>Number(a[0])-Number(b[0])); const sides=[{name:"Gündogar",count:horses.filter(h=>h.sourceSide==="Gündogar").length},{name:"Günbatar",count:horses.filter(h=>h.sourceSide==="Günbatar").length}]; const avg=horses.length?horses.reduce((n,h)=>n+averageScore(h),0)/horses.length:0; return {champions,relations,lineages,years,sides,avg,top:[...horses].sort((a,b)=>averageScore(b)-averageScore(a)).slice(0,5)};},[horses]);
  const maxYear=Math.max(1,...data.years.map(([,n])=>n));
  return <div className="min-h-screen bg-[#f6f8f7] lg:flex"><Sidebar open={open} setOpen={setOpen}/><div className="min-w-0 flex-1 border-[#0b5e3c]/20 sm:border-x-4 lg:border-x-8"><Topbar setOpen={setOpen}/><main className="p-4 text-[#111827] sm:p-6 lg:p-8"><Breadcrumb/><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight text-[#10261d] lg:text-4xl">Tohumçylyk seljermesi</h1><p className="mt-2 font-semibold text-[#526159]">Ähli görkezijiler katalogdaky {horses.length} atdan awtomatik hasaplanýar.</p></div><div className="flex items-center gap-2 rounded-xl border bg-white px-4 py-3 font-bold shadow-sm"><CalendarDays size={19} className="text-[#0b5e3c]"/> {Math.min(...horses.map(h=>h.year))} — {Math.max(...horses.map(h=>h.year))}</div></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat icon={<Shield/>} label="Jemi atlar" value={horses.length}/><Stat icon={<Network/>} label="Nesil baglanyşygy" value={data.relations}/><Stat icon={<Trophy/>} label="Çempion atlar" value={data.champions.length} gold/><Stat icon={<Dna/>} label="Nesil ugurlary" value={data.lineages.length}/><Stat icon={<span className="text-xl font-black">9.0</span>} label="Ortaça baha" value={data.avg.toFixed(1)}/><Stat icon={<HeartPulse/>} label="Doly pasport" value={`${Math.round(horses.filter(h=>h.father&&h.mother&&h.breedingValue).length/Math.max(1,horses.length)*100)}%`}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-12"><Panel title="Nesil ugurlary boýunça paýlanyş" className="xl:col-span-5"><Donut total={horses.length} items={data.lineages.slice(0,6)}/></Panel><Panel title="Ýyllar boýunça doglan atlar" className="xl:col-span-7"><div className="flex h-72 items-end gap-2 border-b border-l px-3 pt-8">{data.years.map(([year,count])=><div key={year} className="flex min-w-[22px] flex-1 flex-col items-center justify-end"><b className="mb-1 text-sm">{count}</b><div className="w-full max-w-10 rounded-t bg-gradient-to-t from-[#07553a] to-[#68a886]" style={{height:`${Math.max(18,count/maxYear*190)}px`}}/><span className="mt-2 -rotate-45 text-xs font-bold text-[#45554d]">{year}</span></div>)}</div></Panel><Panel title="Gündogar / Günbatar paýlanyşy" className="xl:col-span-4"><div className="grid grid-cols-2 gap-4">{data.sides.map((s,i)=><div key={s.name} className="rounded-xl border bg-[#f8faf9] p-5 text-center"><div className="mx-auto mb-3 flex h-16 w-16 items-center justify-center rounded-full text-2xl font-black text-white" style={{background:COLORS[i]}}>{s.count}</div><b className="text-lg">{s.name}</b><p className="font-semibold text-gray-600">{Math.round(s.count/Math.max(1,horses.length)*100)}%</p></div>)}</div></Panel><Panel title="Iň ýokary tohumçylyk bahalary" className="xl:col-span-5"><div className="space-y-1">{data.top.map((h,i)=><a key={h.id} href={`/atlar/${h.id}`} className="grid grid-cols-[34px_1fr_auto] items-center gap-3 rounded-lg px-2 py-3 hover:bg-emerald-50"><span className="font-black text-amber-600">{i<3?["🥇","🥈","🥉"][i]:i+1}</span><span><b className="block">{h.name}</b><small className="font-semibold text-gray-500">{h.lineage}</small></span><b className="text-lg text-[#07553a]">{averageScore(h).toFixed(1)}</b></a>)}</div></Panel><Panel title="Çempionlaryň statistikasy" className="xl:col-span-3"><div className="space-y-3"><Mini label="Çempion atlar" value={data.champions.length}/><Mini label="Gündogar çempionlary" value={data.champions.filter(h=>h.sourceSide==="Gündogar").length}/><Mini label="Günbatar çempionlary" value={data.champions.filter(h=>h.sourceSide==="Günbatar").length}/><Mini label="Çempionlyk derejesi" value={`${Math.round(data.champions.length/Math.max(1,horses.length)*100)}%`}/></div></Panel></div>
  </main></div></div>;
}
function Stat({icon,label,value,gold=false}:{icon:React.ReactNode;label:string;value:number|string;gold?:boolean}){return <div className="rounded-2xl border border-[#dfe7e2] bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className={`${gold?"bg-amber-50 text-amber-600":"bg-emerald-50 text-[#0b5e3c]"} flex h-11 w-11 items-center justify-center rounded-full`}>{icon}</span><span className="text-xs font-black text-emerald-700">JANLY</span></div><p className="mt-4 text-sm font-extrabold text-[#526159]">{label}</p><b className="mt-1 block text-3xl font-black text-[#111827]">{value}</b></div>}
function Panel({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm ${className}`}><h2 className="mb-5 text-xl font-black text-[#15251e]">{title}</h2>{children}</section>}
function Donut({total,items}:{total:number;items:[string,number][]}){let cursor=0;const gradient=items.map(([,n],i)=>{const start=cursor;cursor+=n/Math.max(1,total)*100;return `${COLORS[i%COLORS.length]} ${start}% ${cursor}%`}).join(",");return <div className="flex flex-col items-center gap-6 sm:flex-row"><div className="relative h-52 w-52 shrink-0 rounded-full" style={{background:`conic-gradient(${gradient})`}}><div className="absolute inset-12 flex flex-col items-center justify-center rounded-full bg-white"><b className="text-3xl">{total}</b><span className="font-bold text-gray-500">at</span></div></div><div className="w-full space-y-3">{items.map(([name,n],i)=><div key={name} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 font-bold"><i className="h-3 w-3 rounded-full" style={{background:COLORS[i%COLORS.length]}}/>{name}</span><b>{n}</b></div>)}</div></div>}
function Mini({label,value}:{label:string;value:number|string}){return <div className="flex items-center justify-between rounded-xl bg-[#f5f8f6] px-4 py-4"><span className="font-bold text-[#45554d]">{label}</span><b className="text-xl text-[#07553a]">{value}</b></div>}
