export type Horse = {
  id: string;
  name: string;
  breed: string;
  sex: string;
  color: string;
  year: number;
  code: string;
  image?: string;
  champion: boolean;
  lineage?: string;
  father?: string;
  mother?: string;
  bodyMeasurements?: string;
  breedingValue?: string;
  horseClass?: string;
  description?: string;
  sourceSide?: "Gündogar" | "Günbatar";
  sourceNumber?: number;
};

export type HorseForm = Omit<Horse, "id">;

// Täze açar öňki demo maglumatlaryň localStorage-dan gaýtadan ýüklenmeginiň öňüni alýar.
export const HORSE_STORAGE_KEY = "horse-portal-v3-real-horses";

export const initialHorses: Horse[] = [
  {
    id: "gundogar-01-akyol",
    name: "Akýol",
    breed: "Ahalteke",
    sex: "At",
    color: "Gyr",
    year: 2015,
    code: "GÜNDOGAR-01",
    champion: false,
    lineage: "Eýeberdi Telekäniň nesil ugry",
    father: "Mertebeli — gyr, 2007 (Meýdanly – Aýperi), Eýeberdi Telekäniň nesil ugry",
    mother: "Garagalpak — gara, 2007 (Galkan II – Görkli), Posmanyň nesil ugry",
    bodyMeasurements: "161-161-174-19.0",
    breedingValue: "9.0-8.5-9.0-8.5-8.0",
    horseClass: "Naýbaşy",
    description: "Gahryman Arkadagymyz tarapyndan «Galkynyş» milli at üstündäki oýunlar toparyna Russiýa Federasiýasynyň Sankt-Peterburg şäherinde 2018-nji ýylda geçirilen halkara sirk festiwalyna gatnaşmaga gidende sowgat berildi.",
    sourceSide: "Gündogar",
    sourceNumber: 1,
  },
  {
    id: "gundogar-02-parasat",
    name: "Parasat",
    breed: "Ahalteke",
    sex: "At",
    color: "Dor",
    year: 2012,
    code: "GÜNDOGAR-02",
    image: "/horses/parasat.webp",
    champion: true,
    lineage: "Pereňiň nesil ugry",
    father: "Pyýada — mele, 1990 (Pudak – Bossan), Pereňiň nesil ugry",
    mother: "Gülendam — dor, 2007 (Gala – Gaýtar), Gyrsakaryň nesil ugry",
    bodyMeasurements: "160-163-180-19.0",
    breedingValue: "9.0-8.5-9.0-8.5-9.0",
    horseClass: "Naýbaşy",
    description: "2019-njy ýylda geçirilen «Ýylyň iň owadan ahalteke bedewi» atly halkara gözellik bäsleşiginiň ýeňijisi boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 2,
  },
  {
    id: "gundogar-03-kanun",
    name: "Kanun",
    breed: "Ahalteke",
    sex: "At",
    color: "Gurt mele",
    year: 2004,
    code: "GÜNDOGAR-03",
    champion: false,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Keýmir II — gara, 1987 (Kerwen – Ýelsona), Gyrsakaryň nesil ugry",
    mother: "Sabyrly — mele, 1993 (Teleguş II – Serwi), Meleguşyň nesil ugry",
    bodyMeasurements: "158-160-169-19.0",
    breedingValue: "8.5-8.5-9.5-8.5-7.5",
    horseClass: "Naýbaşy",
    sourceSide: "Gündogar",
    sourceNumber: 3,
  },
  {
    id: "gundogar-04-hankerwen",
    name: "Hankerwen",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2018,
    code: "GÜNDOGAR-04",
    image: "/horses/hankerwen.webp",
    champion: false,
    lineage: "Gaplanyň nesil ugry",
    father: "Hanbegler — mele, 2008 (Bitaraplyk – Gülälek), Gaplanyň nesil ugry",
    mother: "Okgyz — dor, 2010 (Gadymyýet – Owadan), Fakirpalwanyň nesil ugry",
    bodyMeasurements: "160-161-175-18.0",
    breedingValue: "7.5-8.5-8.0-7.5-7.5",
    horseClass: "Naýbaşy",
    description: "Hankerweniň şejere ugrunyň nesilbaşysy meşhur Gaplan 1967-nji ýylda Bütin Soýuz sergisinde ahalteke tohum atlarynyň naýbaşysy diýen ada mynasyp boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 4,
  },
  {
    id: "gundogar-05-dowletli",
    name: "Döwletli",
    breed: "Ahalteke",
    sex: "At",
    color: "Dor",
    year: 2006,
    code: "GÜNDOGAR-05",
    image: "/horses/dowletli.webp",
    champion: false,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Gala — gara, 1997 (Erezgala – Ajaýyp), Gyrsakaryň nesil ugry",
    mother: "Tapylar — mele, 1987 (Köpel – Tolkun), Gyrsakaryň nesil ugry",
    bodyMeasurements: "155-154-161-18.0",
    breedingValue: "7.5-7.0-7.5-7.0-7.0",
    horseClass: "Naýbaşy",
    description: "Döwletli ahalteke bedewine mahsus gylyk-häsiýetini özünde birkemsiz jemlän asyl bedew atdyr.",
    sourceSide: "Gündogar",
    sourceNumber: 5,
  },
  {
    id: "gundogar-06-gerden",
    name: "Gerden",
    breed: "Ahalteke",
    sex: "At",
    color: "Dor",
    year: 2007,
    code: "GÜNDOGAR-06",
    image: "/horses/gerden.webp",
    champion: true,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Gaýduwsyz — gara, 1990 (Garader – Garataý), Gyrsakaryň nesil ugry",
    mother: "Güleken — al, 1998 (Erekdag – Güleý), Gyrsakaryň nesil ugry",
    bodyMeasurements: "163-165-187-19.0",
    breedingValue: "9.5-9.5-9.5-9.0-9.5",
    horseClass: "Naýbaşy",
    description: "2009-njy ýylda Daşkentde geçirilen «Türküstandyň ýyldyzy» atly gözellik bäsleşiginde ýeňiji boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 6,
  },
  {
    id: "gundogar-07-yanardag",
    name: "Ýanardag",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 1991,
    code: "GÜNDOGAR-07",
    image: "/horses/yanardag.webp",
    champion: true,
    lineage: "Fakirpalwanyň nesil ugry",
    father: "Ýalkymly — dor, 1987 (Aýgytly – Ýalançy), Fakirpalwanyň nesil ugry",
    mother: "Dabaraly — gär, 1981 (Senagat – Jahan), Skagyň nesil ugry",
    bodyMeasurements: "161-162-180-19.5",
    breedingValue: "9.5-9.5-9.5-9.0",
    horseClass: "Naýbaşy",
    description: "1999-njy ýylda Moskwada geçirilen halkara gözellik bäsleşiginiň ýeňijisi-çempiony boldy. Bedewiň şekili 2000-nji ýylda Türkmenistanyň Döwlet Tugrasyna geçirildi. Aşgabatda Ýanardagyň heýkeli bina edildi.",
    sourceSide: "Gündogar",
    sourceNumber: 7,
  },
  {
    id: "gundogar-08-ruhybelent",
    name: "Ruhybelent",
    breed: "Ahalteke",
    sex: "At",
    color: "Çakan",
    year: 2017,
    code: "GÜNDOGAR-08",
    champion: false,
    lineage: "Pereňiň nesil ugry",
    father: "Parat — dor, 2007 (Para – Arkalyk), Pereňiň nesil ugry",
    mother: "Gumry — mele, 2001 (Meýdanly – Garaňky), Eýeberdi Telekäniň nesil ugry",
    bodyMeasurements: "158-160-172-18.0",
    breedingValue: "8.5-8.0-8.5-8.0-8.0",
    horseClass: "Naýbaşy",
    description: "Türkmen halkynyň Milli Lideri Gahryman Arkadag lakam goýup, bu bedewi «Galkynyş» milli at üstündäki oýunlar toparyna sowgat berdi.",
    sourceSide: "Gündogar",
    sourceNumber: 8,
  },
  {
    id: "gundogar-09-garader",
    name: "Garader",
    breed: "Ahalteke",
    sex: "At",
    color: "Gara",
    year: 1977,
    code: "GÜNDOGAR-09",
    image: "/horses/garader.webp",
    champion: true,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Kerwen — gara, 1967 (Keýmir – Talant), Gyrsakaryň nesil ugry",
    mother: "Ýelsona — gara, 1972 (Angar – Ýeňiş), Skagyň nesil ugry",
    bodyMeasurements: "162-162-180-19.5",
    breedingValue: "7.0-9.0-9.0-10.0-10.0",
    horseClass: "Naýbaşy",
    description: "Aşgabat, Daşkent, Baku, Almata, Tbilisi, Pýatigorsk, Krasnodar we Rostow aýlawlarynda geçirilen synag at çapyşyklarynda baýrakly orunlara we köp sanly baýraklaryň ýeňijiligine mynasyp boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 9,
  },
  {
    id: "gundogar-10-gadymy",
    name: "Gadymy",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2017,
    code: "GÜNDOGAR-10",
    image: "/horses/gadymy.webp",
    champion: true,
    lineage: "Posmanyň nesil ugry",
    father: "Gadymgala — dor, 2013 (Gadymyýet – Ýelperi), Fakirpalwanyň nesil ugry",
    mother: "Dürli — mele, 2011 (Görkli – Derýalyk), Fakirpalwanyň nesil ugry",
    bodyMeasurements: "162-162-175-19.0",
    breedingValue: "9.0-9.0-9.5-8.5-8.5",
    horseClass: "Naýbaşy",
    description: "2024-nji ýylda geçirilen «Ýylyň iň owadan ahalteke bedewi» atly halkara gözellik bäsleşiginiň ýeňijisi boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 10,
  },
  {
    id: "gundogar-11-beghan",
    name: "Beghan",
    breed: "Ahalteke",
    sex: "At",
    color: "Gyr",
    year: 2008,
    code: "GÜNDOGAR-11",
    image: "/horses/beghan.webp",
    champion: true,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Ýalta — gara, 1998 (Ýantar – Pile), Gyrsakaryň nesil ugry",
    mother: "Akjeren — gyr, 2000 (Garadaşaýak – Aral), Ýeliň nesil ugry",
    bodyMeasurements: "157-159-167-19.0",
    breedingValue: "8.0-8.0-8.5-7.5",
    horseClass: "Naýbaşy",
    description: "2016-njy ýylda geçirilen «Ýylyň iň owadan ahalteke bedewi» atly halkara gözellik bäsleşiginiň ýeňijisi boldy.",
    sourceSide: "Gündogar",
    sourceNumber: 11,
  },
  {
    id: "gundogar-12-altyyap",
    name: "Altyýap",
    breed: "Ahalteke",
    sex: "At",
    color: "Akýal mele",
    year: 2001,
    code: "GÜNDOGAR-12",
    image: "/horses/altyyap.webp",
    champion: false,
    lineage: "Skagyň nesil ugry",
    father: "Altyýap — dor, 1977 (Angar – Garlangaç), Skagyň nesil ugry",
    mother: "Derek — mele, 1989 (Azdepel – Dünýäguş), Eýeberdi Telekäniň nesil ugry",
    bodyMeasurements: "160-161-178-19.0",
    breedingValue: "7.5-7.5-7.5-8.5-7.5",
    horseClass: "Naýbaşy",
    description: "«Galkynyş» milli at üstündäki oýunlar topary bilen dünýäniň birnäçe halkara sirk festiwallarynda üstünlikli çykyş etdi.",
    sourceSide: "Gündogar",
    sourceNumber: 12,
  },
  {
    id: "gunbatar-01-gyrat",
    name: "Gyrat",
    breed: "Ahalteke",
    sex: "At",
    color: "Gyr",
    year: 1999,
    code: "GÜNBATAR-01",
    champion: false,
    lineage: "Ýeliň nesil ugry",
    father: "Garadaşaýak — gara, 1990 (Şahy – Gülendam), Ýeliň nesil ugry",
    mother: "Gülperi — gyr, 1986 (Alwan – Şaperi), Eýeberdi Telekäniň nesil ugry",
    bodyMeasurements: "160-161-170-19.5",
    breedingValue: "8.5-8.5-8.5-8.5-7.5",
    horseClass: "Naýbaşy",
    description: "2010-njy ýylda Beýik Ýeňşiň 65 ýyllygy mynasybetli Moskwada geçirilen dabaraly harby ýörişe gatnaşdy.",
    sourceSide: "Günbatar",
    sourceNumber: 1,
  },
  {
    id: "gunbatar-02-pyyada",
    name: "Pyýada",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 1990,
    code: "GÜNBATAR-02",
    image: "/horses/pyyada.webp",
    champion: true,
    lineage: "Pereňiň nesil ugry",
    father: "Pudak — mele, 1973 (Polatly – Kapliýa), Pereňiň nesil ugry",
    mother: "Bossan — dor, 1981 (Kemal – Bamy), Gaplanyň nesil ugry",
    bodyMeasurements: "159-160-172-19.0",
    breedingValue: "9.5-9.0-9.5-9.5-9.0",
    horseClass: "Naýbaşy",
    description: "2009-njy ýylda Daşkentde geçirilen «Türküstandyň ýyldyzy» atly halkara gözellik bäsleşiginiň ýeňijisi-çempiony boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 2,
  },
  {
    id: "gunbatar-03-gulustan",
    name: "Gülüstan",
    breed: "Ahalteke",
    sex: "At",
    color: "Dor",
    year: 2000,
    code: "GÜNBATAR-03",
    image: "/horses/gulustan.webp",
    champion: true,
    lineage: "Gelşikliň nesil ugry",
    father: "Goar 17 — mele, 1986 (Gauhar 4 – Menaka 15), Gelşikliň nesil ugry",
    mother: "Keseçarka — dor, 1987 (Köpel – Kekene), Gyrsakaryň nesil ugry",
    bodyMeasurements: "161-161-181-19.0",
    breedingValue: "9.5-9.0-8.5-9.5-7.5",
    horseClass: "Naýbaşy",
    description: "Synag at çapyşyklaryna jemi 44 gezek gatnaşyp, 27 gezek birinji, 7 gezek ikinji we 3 gezek üçünji ýere mynasyp boldy; köp sanly baýraklaryň ýeňijisi.",
    sourceSide: "Günbatar",
    sourceNumber: 3,
  },
  {
    id: "gunbatar-04-melebas",
    name: "Melebaş",
    breed: "Ahalteke",
    sex: "At",
    color: "Akýal mele",
    year: 2017,
    code: "GÜNBATAR-04",
    image: "/horses/melebas.webp",
    champion: true,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Gerden — dor, 2007 (Gaýduwsyz – Güleken), Gyrsakaryň nesil ugry",
    mother: "Ýelgamak — mele, 2003 (Goar – Ýelganat), Gelşikliň nesil ugry",
    bodyMeasurements: "161-161-179-19.0",
    breedingValue: "9.5-9.0-8.0-8.5-8.0",
    horseClass: "Naýbaşy",
    description: "2022-nji ýylda geçirilen «Ýylyň iň owadan ahalteke bedewi» atly halkara gözellik bäsleşiginiň ýeňijisi boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 4,
  },
  {
    id: "gunbatar-05-polatly",
    name: "Polatly",
    breed: "Ahalteke",
    sex: "At",
    color: "Altynsow mele",
    year: 1965,
    code: "GÜNBATAR-05",
    champion: true,
    lineage: "Pereňiň nesil ugry",
    father: "Pereň — mele, 1955 (Ýerkus – Pobeda), Skagyň nesil ugry",
    mother: "Gaçgyr — dor, 1951 (Gyrsakar – Mah), Gyrsakaryň nesil ugry",
    bodyMeasurements: "161-162-180-19.5",
    breedingValue: "9.0-10.0-9.0-9.0-9.0",
    horseClass: "Naýbaşy",
    description: "1973-nji we 1977-nji ýyllarda Halk Hojalygynyň Gazananlarynyň Bütin Soýuz sergisiniň ýeňijisi-çempiony boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 5,
  },
  {
    id: "gunbatar-06-hanbeg",
    name: "Hanbeg",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2017,
    code: "GÜNBATAR-06",
    champion: false,
    lineage: "Meleguşyň nesil ugry",
    father: "Toýçy — mele, 1999 (Tyllanur – Aýlar), Meleguşyň nesil ugry",
    mother: "Göwherli — mele, 2005 (Goar 17 – Ganatly), Gelşikliň nesil ugry",
    bodyMeasurements: "162-163-176-19.0",
    breedingValue: "8.5-8.5-8.5-7.5-7.5",
    horseClass: "Naýbaşy",
    description: "Şejere ugrunyň nesilbaşysy Meleguş 1923-nji ýylda Bütin Soýuz sergisinde altyn medala mynasyp boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 6,
  },
  {
    id: "gunbatar-07-garahan",
    name: "Garahan",
    breed: "Ahalteke",
    sex: "At",
    color: "Gara",
    year: 2010,
    code: "GÜNBATAR-07",
    image: "/horses/garahan.webp",
    champion: false,
    lineage: "Gaplanyň nesil ugry",
    father: "Kararym — gara, 2000 (Karar – Maýa), Gaplanyň nesil ugry",
    mother: "Garaaltyn — gara, 2002 (Garadil – Jeren), Gyrsakaryň nesil ugry",
    bodyMeasurements: "158-160-170-19.0",
    breedingValue: "8.5-8.0-8.5-8.0-8.5",
    horseClass: "Naýbaşy",
    description: "Atasy Kararym halkara gözellik bäsleşiginiň jemleýji tapgyryna gatnaşyp, baýrakly orna mynasyp boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 7,
  },
  {
    id: "gunbatar-08-toyly",
    name: "Toýly",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2016,
    code: "GÜNBATAR-08",
    champion: false,
    lineage: "Gaplanyň nesil ugry",
    father: "Hanbegler — mele, 2008 (Bitaraplyk – Gülälek), Gaplanyň nesil ugry",
    mother: "Ýelsona — dor, 2010 (Gadymyýet – Ýelkümüş), Fakirpalwanyň nesil ugry",
    bodyMeasurements: "162-163-174-19.0",
    breedingValue: "9.5-9.0-8.0-8.5-8.0",
    horseClass: "Naýbaşy",
    description: "Türkmenistanyň Prezidentiniň ahalteke atçylyk toplumynda ösdürilip ýetişdirildi.",
    sourceSide: "Günbatar",
    sourceNumber: 8,
  },
  {
    id: "gunbatar-09-bitaraplyk",
    name: "Bitaraplyk",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2012,
    code: "GÜNBATAR-09",
    image: "/horses/bitaraplyk.webp",
    champion: true,
    lineage: "Posmanyň nesil ugry",
    father: "Galkynyş — mele, 2005 (Galkan – Altyn), Posmanyň nesil ugry",
    mother: "Altynaý — gara, 2001 (Arkadaş – Aksoltan), Ýeliň nesil ugry",
    bodyMeasurements: "160-168-173-20.0",
    breedingValue: "8.5-8.5-8.5-7.5-7.5",
    horseClass: "Naýbaşy",
    description: "2015-nji ýylda geçirilen «Ýylyň iň owadan ahalteke bedewi» atly halkara gözellik bäsleşiginiň ýeňijisi boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 9,
  },
  {
    id: "gunbatar-10-miras",
    name: "Miras",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2012,
    code: "GÜNBATAR-10",
    champion: false,
    lineage: "Ýeliň nesil ugry",
    father: "Gaýduwsyz — mele, 2001 (Garadaşaýak – Melegül), Ýeliň nesil ugry",
    mother: "Düşümli — dor, 1999 (Genjaý – Dünýä), Gaplanyň nesil ugry",
    bodyMeasurements: "160-164-179-20.0",
    breedingValue: "7.5-7.5-7.5-7.0-7.0",
    horseClass: "Naýbaşy",
    sourceSide: "Günbatar",
    sourceNumber: 10,
  },
  {
    id: "gunbatar-11-sagadam",
    name: "Şagadam",
    breed: "Ahalteke",
    sex: "At",
    color: "Gyr",
    year: 2007,
    code: "GÜNBATAR-11",
    image: "/horses/sagadam.webp",
    champion: false,
    lineage: "Gyrsakaryň nesil ugry",
    father: "Gyrgyguş — gyr, 1990 (Garader – Gezerli), Gyrsakaryň nesil ugry",
    mother: "Ýelmik — al, 1994 (Gündogar – Ýedigen), Garlawajyň nesil ugry",
    bodyMeasurements: "162-164-180-19.0",
    breedingValue: "8.5-9.0-8.5-8.0-7.5",
    horseClass: "Naýbaşy",
    description: "Gahryman Arkadagymyz tarapyndan «Galkynyş» milli at üstündäki oýunlar toparyna sowgat berildi.",
    sourceSide: "Günbatar",
    sourceNumber: 11,
  },
  {
    id: "gunbatar-12-sahan",
    name: "Şahan",
    breed: "Ahalteke",
    sex: "At",
    color: "Mele",
    year: 2009,
    code: "GÜNBATAR-12",
    image: "/horses/sahan.webp",
    champion: false,
    lineage: "Garlawajyň nesil ugry",
    father: "Şadilli — mele, 1995 (Karal – Sabyrly), Garlawajyň nesil ugry",
    mother: "Ýelgetir — gara, 2002 (Gojagurt – Ýelganat), Gelşikliň nesil ugry",
    bodyMeasurements: "160-163-183-19.5",
    breedingValue: "8.5-8.5-8.5-7.5-7.5",
    horseClass: "Naýbaşy",
    description: "Meşhur Garlawajyň nesil ugruny dowam etdirjek at hökmünde atşynas hünärmenleriň ýokary bahasyna mynasyp boldy.",
    sourceSide: "Günbatar",
    sourceNumber: 12,
  },
];

export function mergeHorseDefaults(horses: Horse[]) {
  return horses.map((horse) => ({
    ...initialHorses.find((item) => item.id === horse.id),
    ...horse,
  }));
}
