"use client";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import Sidebar from "../../components/Sidebar";
import Topbar from "../../components/Topbar";
import Breadcrumb from "../../components/Breadcrumb";
import { useHorseCatalog } from "../../lib/useHorseCatalog";

export default function TohumcylykPage(){const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const{horses}=useHorseCatalog();const visible=useMemo(()=>{const q=query.toLocaleLowerCase("tk").trim();return horses.filter(h=>!q||[h.name,h.code,h.lineage,h.father,h.mother].some(v=>v?.toLocaleLowerCase("tk").includes(q)));},[horses,query]);return <div className="min-h-screen bg-[#f6f8f7] lg:flex"><Sidebar open={open} setOpen={setOpen}/><div className="min-w-0 flex-1 border-[#0b5e3c]/20 sm:border-x-4 lg:border-x-8"><Topbar setOpen={setOpen}/><main className="p-4 text-[#111827] sm:p-6 lg:p-8"><Breadcrumb/><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight text-[#10261d] lg:text-4xl">Tohumçylyk maglumatlary</h1><p className="mt-2 font-semibold text-[#526159]">Jemi {horses.length} at · katalog bilen awtomatik täzelenýär</p></div><label className="relative block w-full lg:max-w-sm"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#526159]" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="At, ID ýa-da nesil boýunça gözle..." className="w-full rounded-xl border-2 border-[#d9e2dd] bg-white py-3 pl-11 pr-4 font-bold shadow-sm outline-none focus:border-[#0b5e3c]"/></label></div><div className="overflow-x-auto rounded-2xl border border-[#dfe7e2] bg-white p-3 shadow-sm"><table className="w-full min-w-[1100px] text-left text-[15px]"><thead><tr className="border-b-2 border-[#a9bbb1] bg-[#f4f7f5]"><th className="p-4">At</th><th className="p-4">ID</th><th className="p-4">Nesil ugry</th><th className="p-4">Atasy</th><th className="p-4">Enesi</th><th className="p-4">Tohumçylyk gymmaty</th></tr></thead><tbody>{visible.map((h,index)=><tr key={h.id} className={`${index%2?"bg-[#fafcfb]":"bg-white"} border-b border-[#e2e8e5] align-top transition hover:bg-emerald-50`}><td className="p-4"><a className="text-base font-black text-[#07553a] hover:underline" href={`/atlar/${h.id}`}>{h.name}</a><span className="mt-1 block text-xs font-bold text-[#66756d]">{h.year} · {h.color}</span></td><td className="p-4 font-extrabold text-[#26352e]">{h.code}</td><td className="p-4 font-bold text-[#26352e]">{h.lineage||"—"}</td><td className="max-w-sm p-4 font-semibold leading-6 text-[#313d37]">{h.father||"—"}</td><td className="max-w-sm p-4 font-semibold leading-6 text-[#313d37]">{h.mother||"—"}</td><td className="p-4 font-black text-[#07553a]">{h.breedingValue||"—"}</td></tr>)}</tbody></table>{!visible.length&&<div className="p-12 text-center font-bold text-gray-600">Gözlege laýyk at tapylmady.</div>}</div></main></div></div>}
